/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Survey } from "./Survey";
import { SurveyCountArgs } from "./SurveyCountArgs";
import { SurveyFindManyArgs } from "./SurveyFindManyArgs";
import { SurveyFindUniqueArgs } from "./SurveyFindUniqueArgs";
import { DeleteSurveyArgs } from "./DeleteSurveyArgs";
import { SurveyService } from "../survey.service";
@graphql.Resolver(() => Survey)
export class SurveyResolverBase {
  constructor(protected readonly service: SurveyService) {}

  async _surveysMeta(
    @graphql.Args() args: SurveyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Survey])
  async surveys(@graphql.Args() args: SurveyFindManyArgs): Promise<Survey[]> {
    return this.service.surveys(args);
  }

  @graphql.Query(() => Survey, { nullable: true })
  async survey(
    @graphql.Args() args: SurveyFindUniqueArgs
  ): Promise<Survey | null> {
    const result = await this.service.survey(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Survey)
  async deleteSurvey(
    @graphql.Args() args: DeleteSurveyArgs
  ): Promise<Survey | null> {
    try {
      return await this.service.deleteSurvey(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
