/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AiDecision } from "./AiDecision";
import { AiDecisionCountArgs } from "./AiDecisionCountArgs";
import { AiDecisionFindManyArgs } from "./AiDecisionFindManyArgs";
import { AiDecisionFindUniqueArgs } from "./AiDecisionFindUniqueArgs";
import { DeleteAiDecisionArgs } from "./DeleteAiDecisionArgs";
import { AiDecisionService } from "../aiDecision.service";
@graphql.Resolver(() => AiDecision)
export class AiDecisionResolverBase {
  constructor(protected readonly service: AiDecisionService) {}

  async _aiDecisionsMeta(
    @graphql.Args() args: AiDecisionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AiDecision])
  async aiDecisions(
    @graphql.Args() args: AiDecisionFindManyArgs
  ): Promise<AiDecision[]> {
    return this.service.aiDecisions(args);
  }

  @graphql.Query(() => AiDecision, { nullable: true })
  async aiDecision(
    @graphql.Args() args: AiDecisionFindUniqueArgs
  ): Promise<AiDecision | null> {
    const result = await this.service.aiDecision(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AiDecision)
  async deleteAiDecision(
    @graphql.Args() args: DeleteAiDecisionArgs
  ): Promise<AiDecision | null> {
    try {
      return await this.service.deleteAiDecision(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
